server:
  port: 8082

spring:
  application:
    name: vehicle-service
  profiles:
    active: neon

---
# Default profile (Docker/Local development)
spring:
  config:
    activate:
      on-profile: default
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/vehicle_db
    username: ${DB_USERNAME:beamerparts_vehicle}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:beamerparts}
    password: ${RABBITMQ_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    live.alinmiron.vehicle_service: DEBUG

---
# Neon profile (Cloud services)
spring:
  config:
    activate:
      on-profile: neon
  
  datasource:
    url: ${NEON_VEHICLE_DB_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: VehicleServiceHikariCP
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          provider_disables_autocommit: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    connect-retries: 3
    connect-retries-interval: 10
  
  rabbitmq:
    addresses:
    - ${RABBITMQ_ADDRESS:localhost}
    connection-timeout: 30000
    requested-heartbeat: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    live.alinmiron.vehicle_service: INFO
