server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: neon
---
# Default profile (Docker/Local development)
spring:
  config:
    activate:
      on-profile: default
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/user_db
    username: ${DB_USERNAME:beamerparts_user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:beamerparts}
    password: ${RABBITMQ_PASSWORD:password}

beamerparts:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-for-development-change-in-production}
    access-token-expiry: 15m
    refresh-token-expiry: 7d
  
  services:
    product-service:
      url: ${PRODUCT_SERVICE_URL:http://localhost:8083}
    vehicle-service:
      url: ${VEHICLE_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    live.alinmiron.user_service: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"

---
# Neon profile (Cloud services)
spring:
  config:
    activate:
      on-profile: neon
  
  datasource:
    url: ${NEON_USER_DB_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: UserServiceHikariCP
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          provider_disables_autocommit: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    connect-retries: 3
    connect-retries-interval: 10
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 5000ms
      ssl:
        enabled: true
      lettuce:
        pool:
          max-active: 2
          max-idle: 2
          min-idle: 0
  
  rabbitmq:
    addresses:
    - ${RABBITMQ_ADDRESS:localhost}
    connection-timeout: 30000
    requested-heartbeat: 30

beamerparts:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-for-development-change-in-production}
    access-token-expiry: 15m
    refresh-token-expiry: 7d
  
  services:
    product-service:
      url: ${PRODUCT_SERVICE_URL:http://localhost:8083}
    vehicle-service:
      url: ${VEHICLE_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    live.alinmiron.user_service: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
