-- User Service - Create User Refresh Tokens Table
-- JWT refresh token management

CREATE TABLE user_refresh_tokens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_revoked BOOLEAN NOT NULL DEFAULT false
);

-- Create indexes for performance (per Phase 1 documentation)
CREATE INDEX idx_user_refresh_tokens_user ON user_refresh_tokens(user_id);
CREATE INDEX idx_user_refresh_tokens_expires ON user_refresh_tokens(expires_at);
