-- User Service - Create User Vehicles Table
-- User's BMW vehicle preferences (uses codes, not foreign keys)

CREATE TABLE user_vehicles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    series_code VARCHAR(10) NOT NULL, -- '3', 'X5', etc.
    generation_code VARCHAR(20) NOT NULL, -- 'F30', 'E90', etc.
    year INTEGER,
    model_variant VARCHAR(100), -- '320i', '330d', etc.
    is_primary BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT ck_user_vehicles_year CHECK (year IS NULL OR (year >= 1950 AND year <= EXTRACT(YEAR FROM CURRENT_DATE) + 2))
);

-- Create indexes for performance (per Phase 1 documentation)
CREATE INDEX idx_user_vehicles_user ON user_vehicles(user_id);
CREATE INDEX idx_user_vehicles_series ON user_vehicles(series_code);
CREATE INDEX idx_user_vehicles_generation ON user_vehicles(generation_code);
