-- User Service - Create Cart Items Table
-- Shopping cart functionality (uses product SKUs, not foreign keys)

CREATE TABLE cart_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_sku VARCHAR(50) NOT NULL, -- 'BMW-F30-AC-001'
    variant_sku VARCHAR(20), -- '-BLK', '-CF', etc.
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL, -- Price snapshot
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT ck_cart_items_quantity CHECK (quantity > 0 AND quantity <= 99),
    CONSTRAINT ck_cart_items_price CHECK (unit_price >= 0),
    CONSTRAINT uk_cart_items_user_product_variant UNIQUE (user_id, product_sku, variant_sku)
);

-- Create indexes for performance (per Phase 1 documentation)
CREATE INDEX idx_cart_items_user ON cart_items(user_id);
CREATE INDEX idx_cart_items_product ON cart_items(product_sku);
CREATE INDEX idx_cart_items_created ON cart_items(created_at);
