-- Product Service - Create Product Variants Table
-- Size, color, material variations

CREATE TABLE product_variants (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL, -- 'Black', 'Carbon Fiber', etc.
    sku_suffix VARCHAR(20) NOT NULL, -- '-BLK', '-CF', etc.
    price_modifier DECIMAL(10,2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uk_product_variants_product_sku UNIQUE (product_id, sku_suffix)
);