-- Product Service - Create Inventory Table
-- Stock tracking and management

CREATE TABLE inventory (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    variant_id BIGINT REFERENCES product_variants(id) ON DELETE CASCADE,
    quantity_available INTEGER NOT NULL DEFAULT 0,
    quantity_reserved INTEGER NOT NULL DEFAULT 0,
    minimum_stock_level INTEGER NOT NULL DEFAULT 5,
    reorder_point INTEGER NOT NULL DEFAULT 10,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT ck_inventory_quantities CHECK (
        quantity_available >= 0 AND 
        quantity_reserved >= 0 AND
        minimum_stock_level >= 0 AND
        reorder_point >= minimum_stock_level
    ),
    CONSTRAINT uk_inventory_product_variant UNIQUE (product_id, variant_id)
);

-- Create indexes for performance (per Phase 1 documentation)
CREATE INDEX idx_inventory_product ON inventory(product_id);
CREATE INDEX idx_inventory_low_stock ON inventory(quantity_available) WHERE quantity_available <= reorder_point;
