-- Product Service - Create Stock Movements Table
-- Stock movement tracking and audit trail

CREATE TABLE stock_movements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    variant_id BIGINT REFERENCES product_variants(id),
    movement_type VARCHAR(20) NOT NULL,
    quantity_change INTEGER NOT NULL,
    reason VARCHAR(100),
    reference_id VARCHAR(50), -- Order number, adjustment ID, etc.
    user_code VARCHAR(255), -- User email or identifier
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT ck_stock_movements_type CHECK (movement_type IN ('INCOMING', 'OUTGOING', 'ADJUSTMENT', 'RESERVED', 'RELEASED'))
);