-- Product Service - Create Product Compatibility Table
-- BMW compatibility mapping using cached data

CREATE TABLE product_compatibility (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    generation_code VARCHAR(20) NOT NULL, -- References bmw_generations_cache(code)
    notes VARCHAR(500),
    is_verified BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uk_product_compatibility UNIQUE (product_id, generation_code),
    CONSTRAINT fk_product_compatibility_generation FOREIGN KEY (generation_code) REFERENCES bmw_generations_cache(code)
);

-- Create indexes for performance (per Phase 1 documentation)
CREATE INDEX idx_product_compatibility_product ON product_compatibility(product_id);
CREATE INDEX idx_product_compatibility_generation ON product_compatibility(generation_code);
