-- Vehicle Service - Create BMW Series Table
-- BMW Series master data

CREATE TABLE bmw_series (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL, -- '3 Series', 'X5', etc.
    code VARCHAR(10) NOT NULL UNIQUE, -- '3', 'X5', etc.
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance (per Phase 1 documentation)
CREATE INDEX idx_bmw_series_code ON bmw_series(code);
CREATE INDEX idx_bmw_series_active ON bmw_series(is_active);
