-- Vehicle Service - Create BMW Generations Table
-- BMW Generations master data

CREATE TABLE bmw_generations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    series_id BIGINT NOT NULL REFERENCES bmw_series(id),
    name VARCHAR(100) NOT NULL, -- 'E46', 'F30/F31/F34/F35', etc.
    code VARCHAR(20) NOT NULL UNIQUE, -- 'E46', 'F30', etc.
    year_start INTEGER NOT NULL,
    year_end INTEGER, -- NULL for current generation
    body_codes TEXT[], -- ['F30', 'F31', 'F34', 'F35'] for variants
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_bmw_generations_series_code UNIQUE (series_id, code),
    CONSTRAINT ck_bmw_generations_years CHECK (year_start > 1950 AND (year_end IS NULL OR year_end >= year_start))
);

-- Create indexes for performance (per Phase 1 documentation)
CREATE INDEX idx_bmw_generations_series ON bmw_generations(series_id);
CREATE INDEX idx_bmw_generations_code ON bmw_generations(code);
CREATE INDEX idx_bmw_generations_active ON bmw_generations(is_active);
