-- Vehicle Service - Create Vehicle Compatibility Registry Table
-- Compatibility registry (uses product SKUs, not foreign keys)

CREATE TABLE vehicle_compatibility_registry (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    generation_id BIGINT NOT NULL REFERENCES bmw_generations(id),
    product_sku VARCHAR(50) NOT NULL, -- 'BMW-F30-AC-001'
    notes VARCHAR(500), -- 'For all 3 Series models'
    is_verified BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uk_vehicle_compatibility UNIQUE (generation_id, product_sku)
);

-- Create indexes for performance (per Phase 1 documentation)
CREATE INDEX idx_vehicle_compatibility_generation ON vehicle_compatibility_registry(generation_id);
CREATE INDEX idx_vehicle_compatibility_product ON vehicle_compatibility_registry(product_sku);
