-- Vehicle Service - Create Vehicle Sync Events Table
-- Event publishing log for synchronization

CREATE TABLE vehicle_sync_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_type VARCHAR(50) NOT NULL, -- 'SERIES_UPDATED', 'GENERATION_UPDATED'
    entity_code VARCHAR(50) NOT NULL, -- Series or generation code
    event_data JSONB NOT NULL, -- Full entity data
    published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processing_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
);

-- Create indexes for performance (per Phase 1 documentation)
CREATE INDEX idx_vehicle_sync_events_status ON vehicle_sync_events(processing_status);
CREATE INDEX idx_vehicle_sync_events_published ON vehicle_sync_events(published_at);
