server:
  port: 8083
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/product_db
    username: ${DB_USERNAME:product_service}
    password: ${DB_PASSWORD:product_password_123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:beamerparts}
    password: ${RABBITMQ_PASSWORD:password}
  
  cache:
    redis:
      time-to-live: 600000 # 10 minutes

beamerparts:
  services:
    vehicle-service:
      url: ${VEHICLE_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    live.alinmiron.product_service: DEBUG
